---
title: "q"
output: html_document
date: "2025-06-05"
---



```{r}
library(igis)
library(pheatmap)
library(dplyr)
library(GenomicRanges)

cwd <- "/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/controlFreeC/"


##########
# get igis 
ig.hg <- Igis(species="mouse", version="4.0")


gt.hg <- genes(ig.hg)

dirs <- grep("SAM",list.files(file.path(cwd), include.dirs = TRUE, full.names = TRUE),invert = FALSE, value = TRUE)

res <- lapply(dirs, function(dir){
  #dir = dirs[1]
  message(dir)
  #f.CNV <- list.files(dir, pattern=".*CNVs.p.value.txt", full.names = TRUE)
  f.ratio <- list.files(dir, pattern=".*ratio.txt$", full.names = TRUE)
  #f.pval <- list.files(dir, pattern=".*p.value.txt$", full.names = TRUE)

# 
#   dt.CNV <- read.table(f.CNV, header=TRUE, sep="\t")
#   gr.CNV <- GRanges(seqnames = dt.CNV$chr,
#                     ranges = IRanges(start = dt.CNV$start,
#                                      end = dt.CNV$end))
#   mcols(gr.CNV) <- dt.CNV

  dt.ratio <- read.table(f.ratio, header=TRUE, sep="\t", stringsAsFactors = FALSE)
  dt.ratio <- cbind(dt.ratio,do.call(rbind,strsplit(sapply(strsplit(dt.ratio$Gene, c(":")),"[[",2), "-")))
  dt.ratio$chr <- dt.ratio$Chromosome; dt.ratio$start <- as.numeric(dt.ratio$`1`); dt.ratio$end <- as.numeric(dt.ratio$`2`)
  gr.ratio <- GRanges(seqnames = dt.ratio$chr,
                      ranges = IRanges(start = dt.ratio$start,
                                       end = dt.ratio$end))
  mcols(gr.ratio) <- dt.ratio
# 
#   dt.pval <- read.table(f.pval, header=TRUE, sep="\t")
#   gr.pval <- GRanges(seqnames = dt.pval$chr,
#                     ranges = IRanges(start = dt.pval$start,
#                                      end = dt.pval$end))
#   mcols(gr.pval) <- dt.pval


 # hits.cnv <- findOverlaps(gt.hg, gr.CNV, ignore.strand = TRUE)
  hits.ratio <- findOverlaps(gt.hg, gr.ratio, ignore.strand = TRUE)
  #hits.pval <- findOverlaps(gt.hg, gr.pval, ignore.strand = TRUE)
  #hits2 <- findOverlaps(tT.annot.gr2, igis.mouse.genes, ignore.strand = TRUE)

  #df.CNV <- data.frame(peak=gt.hg[queryHits(hits.cnv)],gr.CNV[subjectHits(hits.cnv)])
  df.ratio <- data.frame(peak=gt.hg[queryHits(hits.ratio)],gr.ratio[subjectHits(hits.ratio)])
  #df.pval <- data.frame(peak=gt.hg[queryHits(hits.pval)],gr.pval[subjectHits(hits.pval)])

  return(list(ratio=df.ratio))

})

names(res) <- basename(dirs)

saveRDS(res, file.path(cwd, "gene.overlaps.rds"))





```



```{r}


cwd <- "/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/controlFreeC/"

res <- readRDS(file.path(cwd, "gene.overlaps.rds"))



simp.res = lapply(res, function(x) {
  
  
  s.res <-x$ratio %>% select(peak.GeneID, peak.Symbol, CopyNumber) %>% group_by(peak.GeneID, peak.Symbol) %>%
    dplyr::summarise(CopyNumber.median=round(median(CopyNumber)))
})



##### create a big wide table, each column is the median copy number for each sample 

res.cn =simp.res %>%
  Reduce(function(df1, df2) full_join(df1, df2, by = c("peak.GeneID", "peak.Symbol")), .)
colnames(res.cn)= c("ID", "Symbol", names(res))
res.cn = as.data.frame(res.cn)


#### select the highly variable genes 

cn.sd = rowSds(as.matrix(res.cn[, 3:7]), na.rm = T)
cn.mean = rowMeans(as.matrix(res.cn[, 3:7]), na.rm = T)

res.cn.stat = data.frame(ID = res.cn$ID, Symbol = res.cn$Symbol, 
                         sd = cn.sd, mean = cn.mean, stringsAsFactors = F)

saveRDS(res.cn,"/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/controlFreeC/res.cn.rds")
saveRDS(res.cn.stat,"/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/controlFreeC/res.cn.stat.rds")



```