---
title: "crc_revision_ATAC_p5Inhibit_panostat_motif_visual_20250805"
output: html_document
date: "2025-08-05"
---

visualize homer results comparing Panobinostat with P1 and P5 

pano vs P1

```{r}

library(Rmpfr)
library(ggplot2)
library(ggrepel)

pano_p1_up = fread("/gstore/project/crc_metastasis/revision/P5_inhibit_ATAC/HOMER_result/Pano_P1/r0.58_4_up/knownResults.txt", stringsAsFactors = F, data.table = F)

pano_p1_down = fread("/gstore/project/crc_metastasis/revision/P5_inhibit_ATAC/HOMER_result/Pano_P1/r0.58_4_down/knownResults.txt", stringsAsFactors = F, data.table = F)

pano_p5_up = fread("/gstore/project/crc_metastasis/revision/P5_inhibit_ATAC/HOMER_result/Pano_P5/r0.58_4_up/knownResults.txt", stringsAsFactors = F, data.table = F)

pano_p5_down = fread("/gstore/project/crc_metastasis/revision/P5_inhibit_ATAC/HOMER_result/Pano_P5/r0.58_4_down/knownResults.txt", stringsAsFactors = F, data.table = F)



plot_up_rank = function(motif_up,
                        title)
{
  
  # 
  # motif_up = pano_p1_up
  # title = "motifs enriched in Pano vs P1 up "
  # 
motif_name = toupper(gsub("\\(.*","", motif_up[,1]))



motif_sig = -log10(mpfr(motif_up$`P-value`, precBits = 500))

m_df = data.frame(name = motif_name, sig = as.numeric(motif_sig), 
                  stringsAsFactors = F)%>%
  dplyr::mutate(rank = row_number())



 p = ggplot(m_df[1:60,], aes(rank, sig))+
    geom_point(color = "red",
               size = 3) +
    geom_text_repel(data = m_df[1:30,],
                    aes(label = name),
                    color ="black",
                    size = 2,
                    segment.size = 0.3,
                    segment.alpha = 0.3,
                    force = 4,
                    max.overlaps = Inf,
                    box.padding = unit(0.35, "lines"),
                    point.padding = unit(0.3, "lines"),
                    seed = 123)+
    theme_classic()+
    theme(text = element_text(size=10)) +
    ggtitle(title)+
    labs(x="rank", y = "-log10(p-value)")
 
 return(p)
}





plot_down_rank = function(motif_down,
                        title)
{
  
  # 
  # motif_down = pano_p1_down
  # title = "motifs enriched in Pano vs P1 down "
  # 
motif_name = toupper(gsub("\\(.*","", motif_down[,1]))



motif_sig = -log10(mpfr(motif_down$`P-value`, precBits = 500))

m_df = data.frame(name = motif_name, sig = as.numeric(motif_sig), 
                  stringsAsFactors = F)%>%
  dplyr::mutate(rank = row_number())



 p = ggplot(m_df[1:60,], aes(rank, sig))+
    geom_point(color = "blue",
               size = 3) +
    geom_text_repel(data = m_df[1:30,],
                    aes(label = name),
                    color ="black",
                    size = 2,
                    segment.size = 0.3,
                    segment.alpha = 0.3,
                    force = 4,
                    max.overlaps = Inf,
                    box.padding = unit(0.35, "lines"),
                    point.padding = unit(0.3, "lines"),
                    seed = 123)+
    theme_classic()+
    theme(text = element_text(size=10)) +
    ggtitle(title)+
    labs(x="rank", y = "-log10(p-value)")
 
 return(p)
}


```


```{r}

pano_p1_up_plot = plot_up_rank(motif_up = pano_p1_up,
                        title = "motifs enriched in Pano vs P1 up ")
  
  
pano_p5_up_plot = plot_up_rank(motif_up = pano_p5_up,
                        title = "motifs enriched in Pano vs P5 up ")
  
  
pano_p1_down_plot = plot_down_rank(motif_down = pano_p1_down,
                        title = "motifs enriched in Pano vs P1 down ")
  
  
pano_p5_down_plot = plot_down_rank(motif_down = pano_p5_down,
                        title = "motifs enriched in Pano vs P5 down ")
  
  
library(patchwork)

pano_p1_up_plot + pano_p1_down_plot +pano_p5_up_plot+ pano_p5_down_plot
ggsave("/gstore/project/crc_metastasis/revision/P5_inhibit_ATAC/HOMER_result/pano_p1_p5_rank_motif.pdf", 
       width = 8, height = 8)
```




```