---
title: "crc_revision_P12345_mapkFocused_20250605"
output: html_document
date: "2025-06-05"
---


```{r}

library(circlize)
library(ComplexHeatmap)
library(matrixStats)
library(readxl)
library(dplyr)
library(magrittr)
library(data.table)
library(igis)


mapk = read_excel("/gstore/home/lix335/resources/42003_2020_1552_MOESM4_ESM.xlsx",
                  sheet = 1)%>%
  as.data.frame()%>%
  dplyr::select(Gene, Pathway)%>%
  unique()%>%
  dplyr::group_by(Gene)%>%
  dplyr::summarise(pathway = paste(Pathway, collapse = "_"))



ig.mm <- Igis(species = "mouse", version = "4.0")
ig.mm.gt <- data.frame(genes(ig.mm))
ig.hg <- Igis(species = "human", version = "4.0")
ig.hg.gt <- data.frame(genes(ig.hg))


  sig.hg <- genesBySymbol(symbols = unique(mapk$Gene), igis = ig.hg)
  sig.hg.orth <- orthologs(geneIds = sig.hg$GeneID, toSpecies = "mouse",igis = ig.hg)
  sig.mm.orth <- genesById(geneIds = sig.hg.orth$mmusculus_homolog_ensembl_gene, igis = ig.mm)

  
  
### get a df with both human and mouse gene symbols 
  

  hg_mm_df = data.frame(human_symbol = sig.hg.orth$Symbol, mouse_id = sig.hg.orth$mmusculus_homolog_ensembl_gene, stringsAsFactors = F)%>%
    dplyr::left_join(data.frame(mouse_symbol = sig.mm.orth$Symbol, mouse_id =sig.mm.orth$GeneID,stringsAsFactors = F),
                     by = "mouse_id")%>%
    na.omit()%>%
    dplyr::select(human_symbol, mouse_symbol)%>%
    unique()%>%
    dplyr::left_join(mapk, by = c("human_symbol" = "Gene"))

res.cn = readRDS("/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/controlFreeC/res.cn.rds")
uni_cn = res.cn%>%
  dplyr::select(-ID)%>%
  unique()


```


```{r}


#### the thing I am showing are on detailed gene level, the most variable 200 genes 

sel_cn = hg_mm_df%>%
  dplyr::left_join(uni_cn, by = c("mouse_symbol" = "Symbol"))%>%
  dplyr::select(-human_symbol)%>%
  dplyr::filter(pathway!= "ERK5")

#### add chromosome annotation of the genes 

library(biomaRt)
ensembl = useMart("ensembl", dataset = "mmusculus_gene_ensembl")

gene_info = getBM(attributes = c('mgi_symbol', 'chromosome_name'),
                  filters = 'mgi_symbol',
                  values = sel_cn$mouse_symbol,
                  mart = ensembl)

gene_info = rbind(gene_info, data.frame(mgi_symbol =c("Dupd1" ,"Dusp13"),
                                        chromosome_name = c("14","14")))

### manually add chr info for "Dupd1"  "Dusp13"

sel_cn_chr = sel_cn%>%
  dplyr::left_join(gene_info, by = c("mouse_symbol" = "mgi_symbol"))%>%
  dplyr::select(mouse_symbol, chromosome_name, pathway, everything())%>%
  na.omit()



cn_mat =as.matrix(sel_cn_chr[, c(4,5,8,7,6)])
rownames(cn_mat) =sel_cn_chr$mouse_symbol

mapk_fam = sel_cn_chr$pathway
simp_fam = mapk_fam
simp_fam[grepl("_", mapk_fam)] = "multi"


#col_fun_af = colorRamp2(c(0, 2,4), c("darkblue", "white", "darkred"))

col_fun_af = structure(c("darkblue", "white", "darkred"),
                       names = c(1,2,3))

# Define row annotations with colors and text for chromosomes
la = rowAnnotation(
  pathway = simp_fam,
  chromosome = anno_simple(sel_cn_chr$chromosome_name, pch = sel_cn_chr$chromosome_name, pt_size = unit(1, "mm")),
  col = list(
    pathway = c(
      "ERK1/2" = "red4",
      "JNK" = "darkgreen",
      "P38" = "darkorange",
      "multi" = "grey"
    )
  )
)



ta = HeatmapAnnotation(passage =c("P1","P2","P3","P4","P5"),
                        col = list(passage = c(
                                               "P1" = "#2D8686",
                                               "P2" = "lightblue",
                                               "P3" = "gold",
                                               "P4" = "darkorange", 
                                               "P5" = "#862D2D")))


h_cn = Heatmap(as.matrix(cn_mat),
             name = "median gene CN",
        col = col_fun_af,
        row_names_side = "right",
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 7),
        rect_gp = gpar(col = "black", lwd = 0.3),
       left_annotation = la, 
       top_annotation = ta, 
      cluster_rows = T, 
       cluster_columns = F)
        #column_split = factor(c(rep("P1",1), rep("P2",1), rep("P5",1)), levels = c("P1", "P2", "P5")))

saveRDS(h_cn,"/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/heamap_cn.rds")

pdf("/gstore/project/crc_metastasis/revision/P1P2P3P4P5_WES/figures/mapk_sinkala_gene_CN_heatmap_lf_noERK5_20250605.pdf", 
    height = 10, width = 5,
    useDingbats = F)
 draw(h_cn)
 dev.off()



```






