---
title: "crc_revision_mapk_otherUp_pathways_20250428"
output: html_document
date: "2025-04-28"
---

analyzing results from AKPS_2types_gsea_20250214

```{r}

library(dplyr)
library(data.table)
library(magrittr)

library(ggplot2)
library(ggrepel)
library(stringr)

gsea_result = readRDS("/gstore/project/crc_metastasis/AKPS_2types/gsea/gsea_result.rds")



res = gsea_result[[1]]$fgsea

### all the mapk pathways 
tt = grep("^WP_", res$name)

wp_res = res[tt,]


fdf = wp_res%>%
    as.data.frame()%>%
  dplyr::filter(grepl("CANCER", name) == F)%>%
    dplyr::filter(grepl("CARCINOMA", name) == F)%>%
    dplyr::arrange(desc(NES))%>%
    dplyr::filter(NGenes >=10 & NGenes <= 500)%>%
    dplyr::arrange(desc(NGenes))%>%
    dplyr::mutate(sig = -log10(PValue))%>%
    dplyr::mutate(simp_name = gsub("Wp_","",str_to_title(name)))

fdf_sel = fdf%>%
  dplyr::filter(abs(NES)>1 & FDR < 0.05)%>%
  dplyr::arrange(desc(NES))%>%
  dplyr::mutate(cm = "other")%>%
  dplyr::mutate(cm = case_when(grepl("mapk|egfr|erbb", simp_name) ~ "MAPK/EGFR", 
                               grepl("wnt", simp_name) ~ "WNT",
                               grepl("cell_cycle", simp_name) ~ "Cell Cycle",
                               T ~ cm))%>%
   dplyr::mutate(regulation = case_when(NES < 0 ~ "down", 
                                       NES > 0 ~ "up"))


b= ggplot(fdf_sel, aes(x = reorder(simp_name, NES),  y = NES, 
                       color = cm, 
                       fill = sign(NES)*(-log10(FDR))))+
  geom_bar(stat = "identity")+
  scale_fill_gradient2(low = "blue", mid = "white", high = "red")+
  scale_color_manual(values = c("darkorange","steelblue","grey"))+
  coord_flip()+
  theme(axis.text.y = element_text(size = 5), title = "Compare Q61R with G12D")+
  theme_bw()+
  labs(x = NULL)


pdf_name = paste0("/gstore/project/crc_metastasis/AKPS_2types/gsea/split_M2_gsea/bar_wp_gsea_fdr0.05_styled_cellCyle_20250428.pdf")
b
ggsave(pdf_name, width = 10, height = 6)

```

P5 vs P1 

```{r}

gsea_result = readRDS("/gstore/project/crc_metastasis/P5_P1_revisit_20240801/gsea/gsea_result.rds")

res = gsea_result[[1]]$fgsea

### all the mapk pathways 
tt = grep("^WP_", res$name)

wp_res = res[tt,]


fdf_p51 = wp_res%>%
    as.data.frame()%>%
  dplyr::filter(grepl("CANCER", name) == F)%>%
    dplyr::filter(grepl("CARCINOMA", name) == F)%>%
    dplyr::arrange(desc(NES))%>%
    dplyr::filter(NGenes >=10 & NGenes <= 500)%>%
    dplyr::arrange(desc(NGenes))%>%
    dplyr::mutate(sig = -log10(PValue))%>%
    dplyr::mutate(simp_name = gsub("Wp_","",str_to_title(name)))

fdf_sel = fdf_p51%>%
  dplyr::filter(abs(NES)>1 & FDR < 0.05)%>%
  dplyr::arrange(desc(NES))%>%
  dplyr::mutate(cm = "other")%>%
  dplyr::mutate(cm = case_when(grepl("mapk|egfr|erbb", simp_name) ~ "MAPK/EGFR", 
                               grepl("wnt", simp_name) ~ "WNT",
                               grepl("cell_cycle", simp_name) ~ "Cell Cycle",
                               T ~ cm))%>%
   dplyr::mutate(regulation = case_when(NES < 0 ~ "down", 
                                       NES > 0 ~ "up"))


b_p51= ggplot(fdf_sel, aes(x = reorder(simp_name, NES),  y = NES, 
                       color = cm, 
                       fill = sign(NES)*(-log10(FDR))))+
  geom_bar(stat = "identity")+
  scale_fill_gradient2(low = "blue", mid = "white", high = "red")+
  scale_color_manual(values = c("green","darkorange","steelblue","grey"))+
  coord_flip()+
  theme(axis.text.y = element_text(size = 5), title = "Compare Q61R with G12D")+
  theme_bw()+
  labs(x = NULL)


pdf_name = paste0("/gstore/project/crc_metastasis/P5_P1_revisit_20240801/gsea/split_M2_gsea/bar_wp_gsea_fdr0.05_styled_cellCyle_20250428.pdf")
b_p51
ggsave(pdf_name, width = 10, height = 15)

```
joint plot 



```{r}


fdf_mark = fdf%>%
    dplyr::mutate(mark = case_when(NES> 1 & FDR < 0.05 ~ "up",
                                   NES < -1 & FDR < 0.05 ~ "down",
                                   T ~ "none"))
  


fdf_p51_mark = fdf_p51%>%
    dplyr::mutate(mark = case_when(NES> 1 & FDR < 0.05 ~ "up",
                                   NES < -1 & FDR < 0.05 ~ "down",
                                   T ~ "none"))
  

fdf_joint = fdf_p51_mark%>%
  dplyr::left_join(fdf_mark, by = c("name","simp_name"))%>%
  dplyr::mutate(type = case_when(mark.x == "up" &mark.y =="up" ~ "both up", 
                                 mark.x == "down"&mark.y =="down" ~ "both down",
                                 mark.x == "up"& mark.y =="down" ~ "p5upqdown",
                                 mark.x == "down"& mark.y =="up" ~ "p5downqup",
                                 mark.x == "none"& mark.y =="none" ~ "insig",
                                 mark.x == "up" & mark.y == "none" & (grepl("cell_cycle",simp_name) | grepl("mapk",simp_name)) ~ "p5upqnone",
                                 T ~ "other"))%>%
  dplyr::filter(type != "insig")

fdf_joint$NES.x[which(is.na(fdf_joint$NES.x))] = 0 

fdf_joint$NES.y[which(is.na(fdf_joint$NES.y))] = 0 


  wid = max(fdf_joint$NES.x) - min(fdf_joint$NES.x)
  hei = max(fdf_joint$NES.y) - min(fdf_joint$NES.y)
  


pj = ggplot(fdf_joint, aes(NES.y,NES.x))+
    geom_point(aes(color = type,size = NGenes.x),
               alpha = 0.6) +
    scale_colour_manual(values = c("blue","red","grey","darkgreen","darkorange"), name = "", labels = c("both down","both up",  "other",   "p5upqdown","p5upqnone"))+
    geom_hline(yintercept = -1, colour = "black", linetype = "dashed", size = 0.3,alpha = 0.5) +
      geom_hline(yintercept = 1, colour = "black", linetype = "dashed", size = 0.3,alpha = 0.5) +
    geom_vline(xintercept = 1, colour = "black", linetype="dashed", size = 0.3,alpha = 0.5) +
    geom_vline(xintercept = -1, colour = "black", linetype="dashed", size = 0.3,alpha = 0.5) +
    geom_text_repel(data = fdf_joint[which(fdf_joint$type!="other"),],
                    aes(label = simp_name,color = type),
                    size = 3,
                    segment.size = 0.3,
                    segment.alpha = 0.3,
                    force = 4,
                    max.overlaps = Inf,
                    box.padding = unit(0.35, "lines"),
                    point.padding = unit(0.3, "lines"),
                    seed = 123)+
  coord_fixed(ratio =hei/wid)+
  theme_bw()+
    theme(text = element_text(size=10)) +
    ggtitle(paste0(" NES cutoff: ", 1, " FDR cutoff: ",0.05))+
    labs(x="NES Q61R vs G12D", y = "NES P5 vs P1")



pj
ggsave("/gstore/project/crc_metastasis/AKPS_2types/gsea/gsea_compare_scatter_fdr005.pdf", width = 8, height = 6)



```



create a heatmap to show cell cycle genes in Q vs G 


```{r}

expr = fread("/gstore/project/crc_metastasis/AKPS_2types/edit_my_voom-results/filter_lcpm_expression.tsv", 
            stringsAsFactors = F)

res2t = fread("/gstore/project/crc_metastasis/AKPS_2types/res_df.tsv", stringsAsFactors = F, data.table = F)



library(msigdbr)

library(matrixStats)
library(circlize)
library(ComplexHeatmap)

m_t2g <- msigdbr(species = "Mus musculus", category = "C2") %>% 
  dplyr::select(gs_name,gene_symbol)%>%
  dplyr::filter(gs_name == "WP_CELL_CYCLE")

sel_genes = res2t%>%
  dplyr::filter(symbol %in% m_t2g$gene_symbol)%>%
  dplyr::filter(FDR < 0.05)

sel_expr = expr%>%
  dplyr::filter(symbol %in% sel_genes$symbol)



expr_mat = as.matrix(sel_expr[, c(3:10)])
colnames(expr_mat) = colnames(sel_expr)[3:10]
rownames(expr_mat) = sel_expr$symbol



r_m = rowMeans(expr_mat)
r_sd = rowSds(expr_mat)
stan_expr = sweep(expr_mat, 1, r_m)
stan_expr = sweep(stan_expr, 1, r_sd, FUN = "/")

col_fun_expr = colorRamp2(c(-2, 0, 2), c("blue","white", "red"))


ta = HeatmapAnnotation(group =c(rep("G12D",4), rep("Q61R",4)), 
                       col = list(group = c("G12D" = "#2D8686",
                                            "Q61R" = "#862D2D")))

# 
# square_cal = function(n)
# {
#   if(n > 10)
#   {
#       c = ceiling(log10(n))
#   p = n/(10**c)
#   }else{
#       c = ceiling(log10(n))
#   p = n/(100**c)
#   
#   }
# 
#   if(n == 1)
#   {
#     p = 0.01
#   }
#   
#   return(p)
#   
# }
# 
# 
# 
# hei = unit(square_cal(nrow(stan_expr))*50, "cm")


#### awalys get the height and proportionaly get the width 

h1 = Heatmap(as.matrix(stan_expr),
             #width = hei*(ncol(stan_expr)/nrow(stan_expr)),
             #height = unit(square_cal(nrow(stan_expr)), "snpc"),
                          #height =hei,
             name = "standardized expression",
        col = col_fun_expr,
        row_names_side = "right",
        row_names_gp = gpar(fontsize = 5),
        column_names_gp = gpar(fontsize = 4),
        rect_gp = gpar(col = "black", lwd = 0.5),
        #left_annotation = la, 
       top_annotation = ta, 
        cluster_rows = T, cluster_columns = F,
        column_split = factor(c(rep("G12D",4), rep("Q61R",4)), levels = c("G12D", "Q61R")))


res2t = fread("/gstore/project/crc_metastasis/AKPS_2types/res_df.tsv", stringsAsFactors = F, data.table = F)

lf_df = rbindlist(lapply(1:nrow(stan_expr), function(x) {
  this_gene = rownames(stan_expr)[x]
     gp15 = res2t%>%
          dplyr::filter(symbol == this_gene)

    
  df = data.frame(gene = this_gene,
                lf_p15 = NA, 
                fdr_p15 = NA, 
                 sig_p15 = "",
                  stringsAsFactors = F)
 
  if(nrow(gp15) >0)
  {
        df$lf_p15 = gp15$LogFC[1]
        df$fdr_p15 =  gp15$FDR[1]
             if(gp15$FDR[1] <= 0.05)
          df$sig_p15 = "*"

  }
  
  return(df)
  
}))





sig_mat = as.matrix(lf_df[,4])

lf_mat = as.matrix(lf_df[,2])
colnames(lf_mat) ="Q61R vs G12D"
rownames(lf_mat) = lf_df$gene

col_fun = colorRamp2(c(-2, 0,2), c("blue", "white", "red"))

h2 = Heatmap(as.matrix(lf_mat),
             name = "Log2 FC",
             col = col_fun,
             row_names_gp = gpar(fontsize = 5),
             #width = unit(square_cal(nrow(lf_mat))/nrow(lf_mat)*50, "cm"), 
             show_row_names = T,
            #height = unit(square_cal(nrow(lf_mat)), "snpc"),
            height = hei,
        column_names_gp = gpar(fontsize = 7),
         cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%s", sig_mat[i, j]), x, y, gp = gpar(fontsize = 8))
},
        rect_gp = gpar(col = "black", lwd = 0.5),
        cluster_rows = F, cluster_columns = F)


pdf("/gstore/project/crc_metastasis/AKPS_2types/cell_cycle_expr_lf_revision_20250430.pdf", height = 9, width = 7.3, useDingbats = F)
 h1+h2
 dev.off()
 


```




