---
title: "crc_revision_Kras_inhibit_rsc_cbc_signature_20250807"
output: html_document
date: "2025-08-07"
---


## read in CBC and RSC and  Qin et al signatures 
https://www.cell.com/cell/pdf/S0092-8674(23)01221-7.pdf
```{r}

library(dplyr)
library(data.table)
library(magrittr)
library(readxl)

qsig = read_excel("/gstore/project/crc_metastasis/revision/Qin_et_al/mmc3.xlsx", sheet = 2,skip = 4)

qsig_sig = as.data.frame(qsig[,c(1,2)])%>%
  na.omit()%>%
  dplyr::mutate(gene_set = paste0("signature_", ANNOTATION))
colnames(qsig_sig)[1] = "gene"

qsig_de = as.data.frame(qsig[,c(4,5)])%>%
  na.omit()%>%
  dplyr::mutate(gene_set = paste0("DEclust_", CLUSTER))
colnames(qsig_de)[1] = "gene"

qpaths = rbind(qsig_sig[,c(1,3)], qsig_de[,c(1,3)])%>%
  dplyr::select(gene_set, gene)%>%
  dplyr::filter(gene_set %in% c("DEclust_proCSC","DEclust_CSC","DEclust_revCSC",
                                "signature_proCSC","signature_CSC","signature_revCSC"))


### add the RSC and CBC signatures 
rsc = fread("/gstore/home/lix335/resources/rsc_cbc.tsv", 
            stringsAsFactors = F, data.table = F)
colnames(rsc) = c("gene_set","gene")

lit_sets = rbind(qpaths, rsc)

```



## perform GSEA 


```{r}
library(clusterProfiler)


res3d_vehicle = readRDS("/gstore/project/crc_metastasis/Kras_inhibition/extra_res/inhibit3d_veh_res.rds")
res14d_vehicle = readRDS("/gstore/project/crc_metastasis/Kras_inhibition/extra_res/inhibit14d_veh_res.rds")


res_df = res3d_vehicle

geneList = res_df$t
names(geneList) = res_df$symbol
geneList = sort(geneList, decreasing = T)
  

set.seed(47382686)

#y <- GSEA(geneList, TERM2GENE = qpaths, pvalueCutoff = 1, minGSSize = 4, maxGSSize = 700, seed = T)
y <- GSEA(geneList, TERM2GENE = lit_sets, pvalueCutoff = 1, minGSSize = 4, maxGSSize = 700, seed = T)



gsea_res = y@result%>%
  dplyr::mutate(regulation = ifelse(NES>0, "up","down"))

b_3d= ggplot(gsea_res, aes(x = reorder(ID, NES),  y = NES, 
                       color = regulation, 
                       fill = sign(NES)*(-log10(p.adjust))))+
  geom_bar(stat = "identity")+
  geom_text(
    aes(label = sprintf("%.2g", p.adjust)),      # or formatC / scales::scientific
    color = "black",
    hjust = ifelse(gsea_res$NES > 0, 1, 0), # put text just outside the bar ends
    size = 2)+
  scale_fill_gradient2(low = "blue", mid = "white", high = "red")+
  scale_color_manual(values = c("blue","red"))+
  coord_flip()+
  theme(axis.text.y = element_text(size = 5))+
  theme_bw()+
  ggtitle("3D vs Veh")+
  labs(x = NULL)



```


```{r}

res_df = res14d_vehicle

geneList = res_df$t
names(geneList) = res_df$symbol
geneList = sort(geneList, decreasing = T)
  

set.seed(47382686)

#y <- GSEA(geneList, TERM2GENE = qpaths, pvalueCutoff = 1, minGSSize = 4, maxGSSize = 700, seed = T)
y <- GSEA(geneList, TERM2GENE = lit_sets, pvalueCutoff = 1, minGSSize = 4, maxGSSize = 700, seed = T)

gsea_res = y@result%>%
  dplyr::mutate(regulation = ifelse(NES>0, "up","down"))

b_14d= ggplot(gsea_res, aes(x = reorder(ID, NES),  y = NES, 
                       color = regulation, 
                       fill = sign(NES)*(-log10(p.adjust))))+
  geom_bar(stat = "identity")+
  geom_text(
    aes(label = sprintf("%.2g", p.adjust)),      # or formatC / scales::scientific
    color = "black",
    hjust = ifelse(gsea_res$NES > 0, 1, 0), # put text just outside the bar ends
    size = 2)+
  scale_fill_gradient2(low = "blue", mid = "white", high = "red")+
  scale_color_manual(values = c("blue","red"))+
  coord_flip()+
  theme(axis.text.y = element_text(size = 5))+
  theme_bw()+
  ggtitle("16D vs Veh")+
  labs(x = NULL)

```


```{r}

library(patchwork)

b_3d + b_14d
```


```{r}


pdf_name = paste0("/gstore/project/crc_metastasis/revision/Kras_inhibit/revision_Qin_signatures_gsea_barplot.pdf")
b_3d + b_14d
ggsave(pdf_name, width = 14, height = 7)

```



