---
title: "avant_KRAS_mut_survival.Rmd"
output: html_document
date: "2025-11-15"
---



KM plots stratifying KRAS MUT status 





```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/gstore/project/crc_metastasis/gitCode/")

```



```{r, include=TRUE, message=FALSE, warning=FALSE}

library(ggplot2)
library(ggbeeswarm)
library(ggpubr)
library(gridExtra)
library(scuttle)
library(GSVA)
library(ggfortify)
library(ggplot2)
library(survival)
library(survminer)
library(parallel)
library(ggrepel)
library(dplyr)
library(data.table)
library(magrittr)
source("R/human/avant_calgb_survival_functions.R")
```


KM plot

```{r, include=TRUE, message=FALSE, warning=FALSE}

meta = fread("data/human/compiled_meta_avant_table.tsv", stringsAsFactors = F, data.table = F)%>%
  dplyr::mutate(cb = paste(c_mapk, c_wnt, sep = "_"))%>%
  dplyr::mutate(cb = factor(cb, levels  = c("low_high","high_low", "low_low","high_high")))

meta$KRAS[which(is.na(meta$KRAS))] = "unknown"
meta$BRAF_T1799A[which(is.na(meta$BRAF_T1799A))] = "unknown"


  ev = "OS"
    sel_c_feat = which(colnames(meta) == "KRAS")
    sel_c_time = which(colnames(meta) == ev)
    sel_c_event = which(colnames(meta) ==   paste0(ev, ".stat"))
  
  
    set_data = meta[,c(sel_c_time,sel_c_event, sel_c_feat)]
    colnames(set_data) = c("time","event", "feature")
    set_data = set_data%>%
      dplyr::filter(feature != "unknown")
 event = ev
 feature = "KRAS"
  set_data$feature = factor(set_data$feature, levels = c("WT", "MUT"))
 set_data$feature_group = set_data$feature

  colnames(set_data) = c("time","event","feature","feature_group")
  
  
  set_data$time = set_data$time/365
  
  num_event_nz = which(set_data$event == 1)
  num_nevent_nz = which(set_data$event == 0)
  
  
  if(length(num_event_nz)>5 & length(num_nevent_nz)>5)
  {
  
    model_fit <- survfit(Surv(time, event) ~ feature_group , data = set_data)
    
    cpres = coxph(Surv(time, event) ~ feature_group , data = set_data)
    s = summary(cpres)
    
    # 
    p = autoplot(model_fit) +
      labs(x = paste0("\n", event," Time (Years) "), y = paste0(event, " Probabilities \n"),
           title = paste0(feature, 
                          " coef: ", round((s$coefficients[1,1]),3),
                          " p: ",round(s$sctest[3],3),
                          " HR: ", round(exp(s$coefficients[1,1]),3))) +
      theme_bw()+
      theme(plot.title = element_text(size = 9))+
      scale_color_manual(values = c(
                                    "WT" = "purple", "MUT" = "darkgreen"))+
      scale_fill_manual(values = c(
                                   "WT" = "purple", "MUT" = "darkgreen"))
    
    
  }
  
  
p

```

boxplot 
```{r, include=TRUE, message=FALSE, warning=FALSE}


meta_k = meta[which(meta$KRAS!="unknown"),]

library(ggpubr)

b =ggplot(meta_k,aes(KRAS, scores_cmapk))+
  geom_boxplot(aes(fill = KRAS))+
  geom_jitter(width = 0.3)+
  stat_compare_means()+
  theme_bw()

b

```


```{r}
sessionInfo()
```
