---
title: "crc_WES_plot_keyMutation"
output: html_document
date: "2024-12-17"
---


## Key mutations


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/gstore/project/crc_metastasis/gitCode/")



```


```{r, include=TRUE, message=FALSE, warning=FALSE}

library(dplyr)
library(data.table)
library(magrittr)
library(ComplexHeatmap)
library(circlize)
library(ggplot2)

square_cal = function(n)
{
  if(n > 10)
  {
      c = ceiling(log10(n))
  p = n/(10**c)
  }else{
      c = ceiling(log10(n))
  p = n/(100**c)
  
  }

  if(n == 1)
  {
    p = 0.01
  }
  
  return(p)
  
}

non_na = function(x)
{
  
  t = length(which(is.na(x) == F))
  
  return(t)
}


```


### Tile of key mutations 


```{r}

mut_sum = readRDS("data/WES/NGS3660.P0_2.somatic_calls_summary.rds")


sel_mut = mut_sum%>%
  as.data.frame()%>%
  dplyr::select(ID, effects.merged,SAM24400842,SAM24400845,SAM24400853)%>%
  dplyr::filter((is.na(SAM24400842)&is.na(SAM24400845)&is.na(SAM24400853)) == F)%>%
  dplyr::mutate(gene = gsub(",.*","", effects.merged))%>%
  dplyr::mutate(gene = gsub("NA \\| ","", gene))%>%
  dplyr::mutate(isMissense = case_when(grepl("missense", effects.merged) ~ "Missense", 
                                       T ~ ""))%>%
  dplyr::mutate(isNMD = case_when(grepl("NMD_", effects.merged) ~ "NMD", 
                                       T ~ ""))%>%
  dplyr::mutate(isframeshift = case_when(grepl("frameshift_variant", effects.merged) ~ "Frameshift",   #### no one is frameshift
                                       T ~ ""))%>%
  dplyr::mutate(isStartlost = case_when(grepl("start_lost", effects.merged) ~ "Startlost",    ### no one is start loss
                                       T ~ ""))%>%
  dplyr::mutate(isStopgain = case_when(grepl("stop_gained", effects.merged) ~ "Stopgained", 
                                       T ~ ""))%>%
  dplyr::select(-isStartlost)%>%
  dplyr::select(-isframeshift)%>%
  dplyr::mutate(alltype = paste(isMissense, isNMD, isStopgain, sep = ""))
  

tile_mat = sel_mut%>%
  dplyr::select(gene, SAM24400842, SAM24400845 ,SAM24400853 ,alltype)%>%
  dplyr::mutate(SAM24400842 = case_when(is.na(SAM24400842) ~ NA, 
                          T ~ alltype))%>%
  dplyr::mutate(SAM24400845 = case_when(is.na(SAM24400845) ~ NA, 
                          T ~ alltype))%>%
  dplyr::mutate(SAM24400853 = case_when(is.na(SAM24400853) ~ NA, 
                          T ~ alltype))%>%
  dplyr::select(-alltype)
  


tm=as.matrix(tile_mat[, 2:4])
rownames(tm) = tile_mat$gene
colnames(tm) = c("SAM24400842","SAM24400845","SAM24400853")

ta = HeatmapAnnotation(passage =c("P1","P2","P5"),
                       col = list(passage = c("P1" = "#2D8686", "P2"= "#592D86", "P5" = "#862D2D")))

dist_mut = function(x, y) {
  
  x[is.na(x)] = 0
  x[which(x == "Missense")] = 1
  x[which(x == "MissenseNMD")] = 2
  x[which(x == "NMD")] = 3
  x[which(x == "Stopgained")] = 4
  x= as.numeric(x)

  y[is.na(y)] = 0
  y[which(y == "Missense")] = 1
  y[which(y == "MissenseNMD")] = 2
  y[which(y == "NMD")] = 3
  y[which(y == "Stopgained")] = 4
  y= as.numeric(y)

  
    sqrt(sum((x - y)^2))
}


hei = unit(square_cal(nrow(tm))*40, "cm")

hm = Heatmap(tm, 
        name = "mutations", 
        col = structure(c("seagreen","gold","darkorange","maroon"),
                                                names = c("Missense","MissenseNMD","NMD","Stopgained")),
        height = hei, 
        width = hei*(ncol(tm)/nrow(tm)), 
        rect_gp = gpar(col = "black", lwd = 0.5),
        row_names_side = "left",
        row_names_gp = gpar(fontsize = 10),
        column_names_gp = gpar(fontsize = 6),
        top_annotation = ta, 
        clustering_distance_rows = dist_mut, 
        cluster_columns = F
    )



hm

```



### Number of key mutations



```{r}

num_sum = data.frame(sample = c("SAM24400842", "SAM24400845", "SAM24400853" ), 
                     num = apply(sel_mut[, 3:5], 2, non_na), 
                     stringsAsFactors = F)


p = ggplot(data = num_sum, aes(x = sample, y = num))+
  geom_bar(stat = "identity")+
  #scale_fill_manual(values = c("grey", "black"))+
  theme_bw()+
  ggtitle("high confidence variants")

p
```









