---
title: "P5Inhibition_ATAC_PCA"
output: html_document
date: "2025-11-13"
---



make PCA for P5Inhibition ATAC seq data 




```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/gstore/project/crc_metastasis/gitCode/")

```





```{r, include=TRUE, message=FALSE, warning=FALSE}



library(ggplot2)
library(ggrepel)
library(data.table)
library(dplyr)
library(magrittr)
source("R/P5Inhibition/scatter_plot_pca_tsn.R")


setwd("/gstore/project/crc_metastasis/gitCode/")
pc_df = readRDS("data/P5Inhibition/pca_df.rds")




col_code = data.frame(type =c("p5","A485","EPZ004777", "RG108", "p1","Panobinostat"), 
                      color = c("darkblue","maroon","skyblue", "grey","green","orange"))


  mark_t = as.data.frame(table(pc_df$type))%>%
    dplyr::left_join(col_code, by = c("Var1" = "type"))%>%
    dplyr::arrange(Var1)
  

  wid = max(pc_df$PC1) - min(pc_df$PC1)
  hei = max(pc_df$PC2) - min(pc_df$PC2)
  
  
  p1 = ggplot(pc_df, aes(PC1,PC2))+
    geom_point(aes(color = type),
               size = 2) +
    scale_colour_manual(values=mark_t$color, name = "", labels = mark_t$Var1)+
    geom_text_repel(data = pc_df, aes(PC1, PC2, label = type),
                    size = 2,
                    segment.size = 0.3,
                    segment.alpha = 0.3,
                    force = 4,
                    max.overlaps = Inf,
                    box.padding = unit(0.35, "lines"),
                    point.padding = unit(0.3, "lines"),
                    seed = 123)+
    theme_bw()+
    theme(text = element_text(size=7)) +
    coord_fixed(ratio = wid/hei)+
    ggtitle("PCA on binding matrix crc_filtered_tmm")
  
  p1
  
  
```



```{r}
sessionInfo()

```